# Generated by Django 3.2.8 on 2021-10-24 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('13İlinmeyenler', 'Bi̇li̇nmeyenler'), ('Kişisel Gelişim', 'Ki̇şi̇sel Geli̇şi̇m'), ('İlham Al', 'İlham Al'), ('Yatırım Haberleri', 'Yatirim Haberleri̇'), ('Girişimcilik', 'Gi̇ri̇şi̇mci̇li̇k'), ('English News', 'Engli̇sh News'), ('Başarı Hikayeleri', 'Başari Hi̇kayeleri̇')], default='13İlinmeyenler', max_length=50)),
                ('color', models.CharField(choices=[('indigo', 'Indigo'), ('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red'), ('blue', 'Blue'), ('gray', 'Gray'), ('pink', 'Pink')], default='red', max_length=30)),
                ('href', models.SlugField(editable=False, unique=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='postpost')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('desc', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('href', models.SlugField(editable=False, unique=True)),
                ('draft', models.BooleanField(default=True)),
                ('readingtime', models.IntegerField(default=0)),
                ('updated', models.DateTimeField()),
                ('date', models.DateTimeField(editable=False, null=True)),
                ('published', models.DateField(default=django.utils.timezone.now)),
                ('featuredimage', models.ImageField(blank=True, null=True, upload_to='post')),
                ('authorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.categories')),
            ],
            options={
                'ordering': ['-date', '-updated'],
            },
        ),
    ]
