# Generated by Django 3.2.8 on 2021-10-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postType',
            field=models.CharField(default='standard', editable=False, max_length=20),
        ),
    ]
