# Generated by Django 3.2.8 on 2021-10-25 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('audioUrl', models.URLField()),
                ('desc', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('href', models.SlugField(editable=False, unique=True)),
                ('draft', models.BooleanField(default=True)),
                ('readingTime', models.IntegerField(default=0)),
                ('updated', models.DateTimeField()),
                ('date', models.DateTimeField(editable=False, null=True)),
                ('published', models.DateField(default=django.utils.timezone.now)),
                ('featuredimage', models.ImageField(blank=True, null=True, upload_to='post_audio')),
                ('authorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categoriesId', models.ManyToManyField(to='post.Categories')),
            ],
        ),
    ]
