# Generated by Django 3.2.8 on 2021-10-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_audio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postaudio',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
